name = "WMI"
tasks = ["wmic baseboard list full /format:csv",
        "wmic bios list full /format:csv",
        "wmic bootconfig list full /format:csv",
        "wmic cdrom list full /format:csv",
        "wmic computersystem list full /format:csv",
        "wmic cpu list full /format:csv",
        "wmic csproduct list full /format:csv",
        "wmic desktop list full /format:csv",
        "wmic desktopmonitor list full /format:csv",
        "wmic diskdrive list full /format:csv",
        "wmic environment list full /format:csv",
        "wmic loadorder list full /format:csv",
        "wmic logicaldisk list full /format:csv",
        "wmic logon list full /format:csv",
        "wmic memorychip list full /format:csv",
        "wmic memphysical list full /format:csv",
        "wmic netclient list full /format:csv",
        "wmic nic list full /format:csv",
        "wmic nicconfig list full /format:csv",
        "wmic alias os list full /format:csv",
        "wmic port list full /format:csv",
        "wmic printer list full /format:csv",
        "wmic product list full /format:csv",
        "wmic qfe list full /format:csv",
        "wmic recoveros list full /format:csv",
        "wmic registry list full /format:csv",
        "wmic service list full /format:csv",
        "wmic share list full /format:csv",
        "wmic sounddev list full /format:csv",
        "wmic startup list full /format:csv",
        "wmic sysaccount list full /format:csv",
        "wmic sysdriver list full /format:csv",
        "wmic volume list full /format:csv"]